integrated Gitea instance into Jenkins

diff --git a/gitea/userinit/run b/gitea/userinit/run
--- a/gitea/userinit/run
+++ b/gitea/userinit/run
@@ -6,6 +6,29 @@ if [ "$GITEA_USER" -a "$GITEA_PASSWORD" ]; then
 	done
 
 	gitea admin create-user --name "$GITEA_USER" --password "$GITEA_PASSWORD" --email me@localhost >/tmp/init.log
+
+	GITEA_URL="http://localhost:3000"
+	AUTHORIZATION="$(echo -n $GITEA_USER:$GITEA_PASSWORD | base64)"
+
+	TOKEN="$(curl -sf -X POST --url $GITEA_URL/api/v1/users/gitea/tokens -H "Authorization: Basic $AUTHORIZATION" -H "Content-Type: application/json" --data '{"name":"test"}' | sed "s/}//g;s/\"//g" | awk -F: '{ print $NF }')"
+	[ -z "$TOKEN" ] && echo "Could not create token"
+	echo "token = $TOKEN"
+
+	curl -f -X POST "$GITEA_URL/api/v1/orgs" -H "Authorization: token $TOKEN" -H "Content-Type: application/json" -H  "accept: application/json" --data '{"name": "org", "username": "home"}' || echo "Could not create organization"
+
+	curl -f -X POST "$GITEA_URL/api/v1/org/home/repos?access_token=$TOKEN" -H "accept: application/json" -H "content-type: application/json" -d '{"name":"test", "description": "Test repository"}' || echo "Could not create repository"
+	curl -f -X POST "$GITEA_URL/api/v1/org/home/repos?access_token=$TOKEN" -H "accept: application/json" -H "content-type: application/json" -d '{"name":"test2", "description": "Second test repository"}' || echo "Could not create repository 2"
+
+	git config --global user.email "me@localhost"
+	git config --global user.name "Prename Surname"
+
+	git init /tmp/test
+	cd /tmp/test
+	touch README.md
+	git add README.md
+	git commit -m "initial commit"
+	git remote add origin http://localhost:3000/home/test.git
+	git push
 fi
 
 while [ 1 ]; do
